version: '3'

services:
  web:
    build: .
    container_name: django_gunicorn_private
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
      - main_storage:/app/main_storage
      - sequestered_incoming:/app/sequestered_incoming
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - SERVER_ROLE=private
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - REDIS_URL=redis://redis:6379/0
      - PUBLIC_REDIS_URL=${PUBLIC_REDIS_URL}
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_django_private
    restart: unless-stopped
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backup:/backup
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 6

  redis:
    image: redis:7
    container_name: redis_private
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  celery-worker:
    build: .
    container_name: celery_worker_private
    restart: unless-stopped
    command: celery -A archive worker -Q private,common
    volumes:
      - main_storage:/app/main_storage
      - sequestered_incoming:/app/sequestered_incoming
    env_file:
      - .env
    environment:
      - SERVER_ROLE=private
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - REDIS_URL=${PUBLIC_REDIS_URL}
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    container_name: celery_beat_private
    restart: unless-stopped
    command: celery -A archive beat
    volumes:
      - main_storage:/app/main_storage
    env_file:
      - .env
    environment:
      - SERVER_ROLE=private
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - REDIS_URL=${PUBLIC_REDIS_URL}
    depends_on:
      - db
      - redis

  virus-scanner:
    build: ./virus-scanner
    container_name: virus_scanner_private
    restart: unless-stopped
    volumes:
      - sequestered_incoming:/scan/incoming:ro
      - main_storage:/scan/main:rw
    environment:
      - SERVER_ROLE=private
      - SCAN_INTERVAL=300  # Scan every 5 minutes

  sync-service:
    build: ./sync-service
    container_name: sync_service_private
    restart: unless-stopped
    volumes:
      - main_storage:/data/main:ro
    environment:
      - SERVER_ROLE=private
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - SYNC_INTERVAL=3600  # Sync every hour

  nginx:
    build: ./nginx
    container_name: nginx_private
    restart: unless-stopped
    volumes:
      - static_volume:/app/static/
    expose:
      - 8081
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  redis_data:
  main_storage:         # Main private storage
  sequestered_incoming: # Quarantine for uploaded and transferred files

networks:
  default:
    external: true
    name: nginxproxymanager_default 