services:
  web:
    build: .
    container_name: django_gunicorn
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_django
    restart: unless-stopped
    expose:
      - "54322"
    command: ["bash", "/docker-entrypoint-initdb.d/init-db.sh"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backup:/backup
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DBUSER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    restart: unless-stopped
    volumes:
      - static_volume:/app/static/
    expose:
      - 8081
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

networks:
  default:
    external: true
    name: nal-archive_default
