version: '3.7'

services:
  web:
    build: .
    container_name: django_gunicorn
    volumes:
      - static:/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_django
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    volumes:
      - static:/static/
    expose:
      - 8081
    depends_on:
      - web

volumes:
  postgres_data:
  static:

networks:
  default:
    external: true
    name: nginxproxymanager_default
