# Generated by Django 3.0.5 on 2021-07-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20210310_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='original_format_medium',
            field=models.CharField(blank=True, choices=[('audio_cd', 'audio CD'), ('audio_reel', 'audio reel'), ('book', 'book'), ('cassette', 'cassette'), ('cd', 'CD'), ('cd_dvd', 'CD-DVD'), ('dat', 'DAT'), ('cd_r', 'data CD (CD-R)'), ('dv_r', 'data DVD (DV-R)'), ('diskette', 'diskette'), ('dvd', 'DVD'), ('ephemera', 'ephemera'), ('garment', 'garment'), ('hi_8', 'hi-8'), ('manuscript', 'manuscript'), ('microcassette', 'microcassette'), ('mini_DV', 'mini-DV'), ('other', 'other'), ('phonograph_record', 'phonograph record'), ('reel_to_reel', 'reel-to-reel'), ('vhs', 'VHS'), ('video_reel', 'video reel')], max_length=17),
        ),
    ]
