# Generated by Django 3.0.5 on 2023-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20210711_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descriptive_materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='educational_materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='music',
            field=models.TextField(blank=True),
        ),
    ]
