# Generated by Django 3.0.5 on 2023-03-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_auto_20230122_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columns_export',
            old_name='item_educational_materials',
            new_name='item_educational_materials_text',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='educational_materials',
            new_name='educational_materials_text',
        ),
    ]
