# Generated by Django 3.0.5 on 2023-03-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_auto_20230308_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columns_export',
            old_name='item_music',
            new_name='item_music_text',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='music',
            new_name='music_text',
        ),
    ]
