# Generated by Django 3.0.5 on 2023-03-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_auto_20230309_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descriptive_materials',
            field=models.CharField(blank=True, choices=[('dictionaries', 'Dictionaries'), ('grammars', 'Grammars'), ('transcribed_texts', 'Transcribed Texts')], max_length=17),
        ),
        migrations.AddField(
            model_name='item',
            name='music',
            field=models.CharField(blank=True, choices=[('ceremonial', 'Ceremonial'), ('war_dance', 'War Dance'), ('round_dance', 'Round Dance'), ('stomp_dance', 'Stomp Dance'), ('49', '49'), ('sundance', 'Sundance'), ('powwow', 'Powwow'), ('hand_game', 'Hand Game'), ('nac', 'NAC'), ('hymns', 'Hymns'), ('children', 'Children')], max_length=11),
        ),
    ]
