# Generated by Django 3.0.5 on 2023-03-11 18:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0018_auto_20230310_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descriptive_materials',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dictionaries', 'Dictionaries'), ('grammars', 'Grammars'), ('transcribed_texts', 'Transcribed Texts')], max_length=39),
        ),
        migrations.AlterField(
            model_name='item',
            name='music',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ceremonial', 'Ceremonial'), ('war_dance', 'War Dance'), ('round_dance', 'Round Dance'), ('stomp_dance', 'Stomp Dance'), ('49', '49'), ('sundance', 'Sundance'), ('powwow', 'Powwow'), ('hand_game', 'Hand Game'), ('nac', 'NAC'), ('hymns', 'Hymns'), ('children', 'Children')], max_length=92),
        ),
    ]
