# Generated by Django 3.0.5 on 2023-03-11 22:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_auto_20230311_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descriptive_materials',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dictionaries', 'Dictionaries'), ('grammars', 'Grammars'), ('transcribed_texts', 'Transcribed texts')], max_length=39),
        ),
        migrations.AlterField(
            model_name='item',
            name='music',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ceremonial', 'Ceremonial'), ('war_dance', 'War dance'), ('round_dance', 'Round dance'), ('stomp_dance', 'Stomp dance'), ('49', '49'), ('sundance', 'Sundance'), ('powwow', 'Powwow'), ('hand_game', 'Hand game'), ('nac', 'NAC'), ('hymns', 'Hymns'), ('children', 'Children')], max_length=92),
        ),
    ]
