# Generated by Django 3.2 on 2024-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0020_auto_20230311_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='dialects',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='dialects_ids',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='family_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='language',
            name='glottocode',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='language_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='language',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('family', 'Family'), ('language', 'Language'), ('dialect', 'dialect')], default='language', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='pri_subgroup_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='language',
            name='sec_subgroup_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='language',
            name='tribes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
