# Generated by Django 3.2 on 2024-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0021_auto_20240422_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='alt_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alternate names'),
        ),
        migrations.AlterField(
            model_name='language',
            name='dialects_ids',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dialect glottocodes'),
        ),
        migrations.AlterField(
            model_name='language',
            name='family_id',
            field=models.CharField(blank=True, max_length=8, verbose_name='Family glottocode'),
        ),
        migrations.AlterField(
            model_name='language',
            name='pri_subgroup',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primary subgroup'),
        ),
        migrations.AlterField(
            model_name='language',
            name='pri_subgroup_id',
            field=models.CharField(blank=True, max_length=8, verbose_name='Primary subgroup glottocode'),
        ),
        migrations.AlterField(
            model_name='language',
            name='sec_subgroup',
            field=models.CharField(blank=True, max_length=255, verbose_name='Secondary subgroup'),
        ),
        migrations.AlterField(
            model_name='language',
            name='sec_subgroup_id',
            field=models.CharField(blank=True, max_length=8, verbose_name='Secondary subgroup glottocode'),
        ),
    ]
