# Generated by Django 3.2 on 2024-04-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0022_auto_20240422_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='family_abbrev',
            field=models.CharField(blank=True, max_length=255, verbose_name='Family abbreviation'),
        ),
        migrations.AddField(
            model_name='language',
            name='pri_subgroup_abbrev',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primary subgroup abbreviation'),
        ),
        migrations.AddField(
            model_name='language',
            name='sec_subgroup_abbrev',
            field=models.CharField(blank=True, max_length=255, verbose_name='Secondary subgroup abbreviation'),
        ),
    ]
