# Generated by Django 3.2 on 2024-05-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_auto_20240423_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columns_export',
            old_name='item_descriptive_materials',
            new_name='item_language_description_type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descriptive_materials',
            new_name='language_description_type',
        ),
    ]
