# Generated by Django 3.2 on 2024-05-06 14:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0024_auto_20240504_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language_description_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lexicon-dictionary', 'Lexicon: Dictionary'), ('grammar', 'Grammar'), ('transcribed_texts', 'Transcribed texts')], max_length=44),
        ),
    ]
