# Generated by Django 3.2 on 2024-05-07 09:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0025_alter_item_language_description_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language_description_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('primary-text', 'Primary text'), ('primary-text-igt', 'Primary text: IGT'), ('grammar', 'Grammar'), ('grammar-sketch', 'Grammar: Sketch'), ('grammar-specific-feature', 'Grammar: Specific feature'), ('lexicon', 'Lexicon'), ('lexicon-dictionary', 'Lexicon: Dictionary'), ('lexicon-wordlist', 'Lexicon: Wordlist'), ('transcript', 'Transcript'), ('translation', 'Translation'), ('comparative', 'Comparative'), ('fieldnotes', 'Field notes'), ('transcribed_texts', 'Transcribed texts')], max_length=185),
        ),
    ]
