# Generated by Django 3.2 on 2024-05-07 13:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0026_alter_item_language_description_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('49', '49'), ('article', 'Article'), ('book', 'Book'), ('ceremony', 'Ceremony'), ('ceremonial', 'Ceremonial'), ('chant', 'Chant'), ('conversation', 'Conversation'), ('correspondence', 'Correspondence'), ('curse', 'Curse'), ('dataset', 'Dataset'), ('debate', 'Debate'), ('description', 'Description'), ('document', 'Document'), ('drama', 'Drama'), ('educational', 'Educational material'), ('educational_material_family', 'Educational materials - Family'), ('educational_material_learners', 'Educational materials - For learners'), ('educational_material_teachers', 'Educational materials - For teachers'), ('educational_materials_planning', 'Educational materials - Language planning'), ('elicitation', 'Elicitation'), ('ethnography', 'Ethnography'), ('field_notes', 'Field notes'), ('for_children', 'For children'), ('grammar', 'Grammar'), ('greeting', 'Greeting/Leave-taking'), ('hand_game', 'Hand game'), ('history', 'History'), ('hymn', 'Hymn'), ('instructions', 'Instructions'), ('instrumental', 'Instrumental music'), ('interview', 'Interview'), ('lexicon', 'Lexicon'), ('meeting', 'Meeting'), ('music', 'Music'), ('myth', 'Myth'), ('narrative', 'Narrative'), ('native_american_church', 'Native American Church'), ('oratory', 'Oratory'), ('photograph', 'Photograph'), ('poetry', 'Poetry'), ('popular_production', 'Popular production'), ('powwow', 'Powwow'), ('prayer', 'Prayer'), ('procedure', 'Procedure'), ('proverb', 'Proverb'), ('reader', 'Reader'), ('recipe', 'Recipe'), ('ritual', 'Ritual song'), ('round_dance', 'Round dance'), ('sketch', 'Sketch'), ('song', 'Song'), ('speech', 'Speech play'), ('stomp_dance', 'Stomp dance'), ('sundance', 'Sundance'), ('textbook', 'Textbook'), ('thesis', 'Thesis'), ('traditional_story', 'Traditional story'), ('transcript', 'Transcript'), ('translation', 'Translation'), ('unintelligible', 'Unintelligible speech'), ('war_dance', 'War dance'), ('wordlist', 'Wordlist')], max_length=674),
        ),
    ]
