# Generated by Django 3.2 on 2024-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0029_alter_item_general_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='general_content',
            field=models.CharField(blank=True, choices=[('3d_object', '3D Object'), ('audio', 'Audio'), ('audio-video', 'Audio/Video'), ('book', 'Book'), ('dataset', 'Dataset'), ('ephemera', 'Ephemera'), ('image', 'Image (Photograph)'), ('manuscript', 'Manuscript'), ('multimedia', 'Multimedia'), ('other', 'Other'), ('publication_article', 'Publication: Journal Article'), ('publication_book', 'Publication: Book'), ('publication_chapter', 'Publication: Book chapter'), ('publication_other', 'Publication (other)'), ('publication_thesis', 'Publication: Thesis'), ('website', 'Website')], max_length=30),
        ),
    ]
