# Generated by Django 3.2 on 2024-05-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0031_remove_item_educational_materials_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columns_export',
            name='item_educational_materials',
        ),
        migrations.RemoveField(
            model_name='columns_export',
            name='item_music',
        ),
        migrations.RemoveField(
            model_name='item',
            name='music',
        ),
        migrations.RemoveField(
            model_name='item',
            name='music_text',
        ),
    ]
