# Generated by Django 3.2 on 2024-05-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0032_auto_20240508_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descriptive_materials_text',
        ),
    ]
