# Generated by Django 3.2 on 2024-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0036_alter_item_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='migrate',
            field=models.BooleanField(default=False),
        ),
    ]
