# Generated by Django 3.2 on 2024-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0037_item_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='glottocode',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
