# Generated by Django 3.2 on 2024-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0038_alter_language_glottocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
