# Generated by Django 3.2 on 2024-05-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0039_alter_language_iso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_item', to='metadata.item')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_language', to='metadata.language')),
            ],
        ),
    ]
