# Generated by Django 3.2 on 2024-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0040_itemtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtitle',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
