# Generated by Django 3.2 on 2024-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0042_alter_item_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='firstname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
