# Generated by Django 3.2 on 2024-06-24 11:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0043_auto_20240530_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('article', 'Article'), ('book', 'Book'), ('ceremonial', 'Ceremonial'), ('conversation', 'Conversation'), ('correspondence', 'Correspondence'), ('dataset', 'Dataset'), ('document', 'Document'), ('drama', 'Drama'), ('educational', 'Educational material'), ('educational_material_family', 'Educational materials: Family'), ('educational_material_learners', 'Educational materials: For learners'), ('educational_material_teachers', 'Educational materials: For teachers'), ('educational_material_planning', 'Educational materials: Language planning'), ('elicitation', 'Elicitation'), ('ethnography', 'Ethnography'), ('history', 'History'), ('interview', 'Interview'), ('music', 'Music'), ('music_forty_nine', 'Music: 49'), ('music_ceremonial', 'Music: Ceremonial'), ('music_for_children', 'Music: For children'), ('music_hand_game', 'Music: Hand game'), ('music_hymn', 'Music: Hymn'), ('music_native_american_church', 'Music: Native American Church'), ('music_powwow', 'Music: Powwow'), ('music_round_dance', 'Music: Round dance'), ('music_stomp_dance', 'Music: Stomp dance'), ('music_sundance', 'Music: Sundance'), ('music_war_dance', 'Music: War dance'), ('narrative', 'Narrative'), ('oratory', 'Oratory'), ('photograph', 'Photograph'), ('poetry', 'Poetry'), ('popular_production', 'Popular production'), ('prayer', 'Prayer'), ('procedural', 'Procedural'), ('saying_proverb', 'Saying or Proverb'), ('speech_play', 'Speech play'), ('textbook', 'Textbook'), ('thesis', 'Thesis'), ('traditional_story', 'Traditional story'), ('transcript', 'Transcript'), ('translation', 'Translation'), ('unintelligible', 'Unintelligible speech')], max_length=613),
        ),
    ]
