# Generated by Django 3.2 on 2024-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0044_alter_item_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_abbr', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True, verbose_name='collection description of scope and content')),
                ('background', models.TextField(blank=True, verbose_name='background information')),
                ('conventions', models.TextField(blank=True, verbose_name='description of arrangement, collector conventions')),
                ('access_statement', models.TextField(blank=True, verbose_name='access/use statement')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['collection_abbr'],
            },
        ),
    ]
