# Generated by Django 3.2 on 2024-08-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0047_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='extent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
