# Generated by Django 3.2 on 2024-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0048_collection_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='acquisition',
            field=models.TextField(blank=True, verbose_name='acquisition information'),
        ),
        migrations.AddField(
            model_name='collection',
            name='citation_authors',
            field=models.TextField(blank=True, verbose_name='citation authors'),
        ),
        migrations.AddField(
            model_name='collection',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='collection_languages', to='metadata.Language', verbose_name='list of languages'),
        ),
    ]
