# Generated by Django 3.2 on 2024-08-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0049_auto_20240813_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_abbr',
            field=models.CharField(max_length=10),
        ),
    ]
