# Generated by Django 3.2 on 2024-08-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0050_alter_collection_collection_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date_range',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
