# Generated by Django 3.2 on 2024-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0051_collection_date_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
