# Generated by Django 3.2 on 2024-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0052_collection_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='dialects_languoids',
            field=models.ManyToManyField(blank=True, related_name='language_dialects_languoids', to='metadata.Language', verbose_name='Dialects languoids'),
        ),
    ]
