# Generated by Django 3.2 on 2024-09-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0053_language_dialects_languoids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='dialects_languoids',
            field=models.ManyToManyField(blank=True, related_name='_metadata_language_dialects_languoids_+', to='metadata.Language', verbose_name='Dialects languoids'),
        ),
    ]
