# Generated by Django 3.2 on 2025-02-20 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0056_auto_20241015_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtitle',
            options={'ordering': ['item', 'title']},
        ),
        migrations.AddField(
            model_name='itemtitle',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtitle',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemtitle',
            name='modified_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtitle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
