# Generated by Django 3.2 on 2025-02-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0057_auto_20250220_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='general_content',
            new_name='resource_type',
        ),
    ]
