# Generated by Django 3.2 on 2025-02-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0058_rename_general_content_item_resource_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columns_export',
            old_name='item_general_content',
            new_name='item_resource_type',
        ),
    ]
