# Generated by Django 3.2 on 2025-02-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0059_rename_item_general_content_columns_export_item_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
