# Generated by Django 3.2 on 2025-02-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0061_populate_item_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
