# Generated by Django 3.2 on 2025-02-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0064_auto_20250227_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
