# Generated by Django 3.2 on 2025-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0065_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
