# Generated by Django 3.2 on 2025-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0067_populate_collection_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
