# Generated by Django 3.2 on 2025-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0072_rename_language_to_languoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='languoid',
            name='alt_names',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Alternative names'),
        ),
    ]
