# Generated by Django 3.2 on 2025-03-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0073_languoid_alt_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='item_count',
            field=models.IntegerField(default=0, help_text='Number of items in this collection'),
        ),
    ]
