# Generated by Django 3.2 on 2025-03-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0074_collection_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date_range_max',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='date_range_min',
            field=models.DateField(blank=True, null=True),
        ),
    ]
