# Generated by Django 3.2 on 2025-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0076_auto_20250331_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='expecting_additions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='related_publications_collections',
            field=models.TextField(blank=True, verbose_name='related publications/collections'),
        ),
    ]
