# Generated by Django 3.2 on 2025-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0078_auto_20250331_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
