# Generated by Django 3.2 on 2025-03-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0079_auto_20250331_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_abbr',
            field=models.CharField(max_length=10, verbose_name='collection abbreviation'),
        ),
    ]
