# Generated by Django 3.2 on 2025-05-18 20:56

from django.db import migrations, models


def set_citation_author_for_existing_roles(apps, schema_editor):
    CollaboratorRole = apps.get_model('metadata', 'CollaboratorRole')
    # Update all existing roles that are authors or performers
    # Since role is a MultiSelectField, we need to check if the role list contains these values
    for role in CollaboratorRole.objects.all():
        if role.role and ('author' in role.role or 'performer' in role.role):
            role.citation_author = True
            role.save(update_fields=['citation_author'])


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0082_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='citation_author',
            field=models.BooleanField(default=False, verbose_name='Citation author'),
        ),
        migrations.RunPython(
            set_citation_author_for_existing_roles,
            reverse_code=migrations.RunPython.noop
        ),
    ]
