# Generated by Django 3.2 on 2025-05-18 22:06

from django.db import migrations, models
import base58
import uuid


def generate_uuids_and_slugs(apps, schema_editor):
    Collaborator = apps.get_model('metadata', 'Collaborator')
    for collaborator in Collaborator.objects.all():
        # Generate new UUID
        collaborator.uuid = uuid.uuid4()
        # Generate slug from UUID
        encoded = base58.b58encode(collaborator.uuid.bytes).decode()[:10]
        collaborator.slug = f"{encoded[:5]}-{encoded[5:10]}"
        collaborator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0083_add_citation_author_to_collaboratorrole'),
    ]

    operations = [
        # First add the UUID field without unique constraint
        migrations.AddField(
            model_name='collaborator',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Then add the slug field without unique constraint
        migrations.AddField(
            model_name='collaborator',
            name='slug',
            field=models.CharField(max_length=20, blank=True, editable=False),
        ),
        # Generate UUIDs and slugs for all existing records
        migrations.RunPython(generate_uuids_and_slugs),
        # Now add the unique constraints
        migrations.AlterField(
            model_name='collaborator',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='slug',
            field=models.CharField(max_length=20, unique=True, editable=False),
        ),
    ]
