# Generated by Django 5.0.14 on 2025-10-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0084_add_slug_to_collaborator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='languoid',
            name='descendents',
            field=models.ManyToManyField(blank=True, related_name='ancestors', to='metadata.languoid', verbose_name='Descendents'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='birthdate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='deathdate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='creation_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='creation_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='accession_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('restrictions', 'Restrictions apply'), ('missing_parts', 'Missing parts'), ('missing', 'Missing')], max_length=13),
        ),
        migrations.AlterField(
            model_name='item',
            name='cataloged_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='creation_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='deposit_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='languoid',
            name='dialects_languoids',
            field=models.ManyToManyField(blank=True, related_name='parent_language_of_dialect', to='metadata.languoid', verbose_name='Dialects languoids'),
        ),
        migrations.AlterField(
            model_name='languoid',
            name='level',
            field=models.CharField(choices=[('family', 'Family'), ('subfamily', 'Primary Subfamily'), ('subsubfamily', 'Secondary Subfamily'), ('language', 'Language'), ('dialect', 'Dialect')], max_length=15),
        ),
    ]
