# Generated by Django 5.0.14 on 2025-10-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0085_delete_video_languoid_descendents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languoid',
            name='name_abbrev',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name abbreviation'),
        ),
        migrations.AddField(
            model_name='languoid',
            name='name_for_glottocode_on_glottolog',
            field=models.CharField(blank=True, max_length=255, verbose_name='Glottolog name'),
        ),
    ]
