# Generated by Django 5.0.14 on 2025-10-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0086_add_languoid_name_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languoid',
            old_name='level',
            new_name='level_nal',
        ),
    ]
