# Generated by Django 5.0.14 on 2025-10-27 01:09

from django.db import migrations, models


def copy_level_nal_to_glottolog(apps, schema_editor):
    """
    Copy level_nal values to level_glottolog, mapping NAL's 5-level system 
    to Glottolog's 3-level system:
    - 'subfamily' and 'subsubfamily' → 'family' (Glottolog doesn't have subfamilies)
    - 'family', 'language', 'dialect' → stay the same
    """
    Languoid = apps.get_model('metadata', 'Languoid')
    
    # Map NAL levels to Glottolog levels
    level_mapping = {
        'family': 'family',
        'subfamily': 'family',        # Map subfamily to family
        'subsubfamily': 'family',     # Map subsubfamily to family
        'language': 'language',
        'dialect': 'dialect',
    }
    
    for languoid in Languoid.objects.all():
        # Get the NAL level and map it to Glottolog level
        nal_level = languoid.level_nal
        glottolog_level = level_mapping.get(nal_level, nal_level)
        
        # Set the Glottolog level
        languoid.level_glottolog = glottolog_level
        languoid.save(update_fields=['level_glottolog'])


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: clear level_glottolog values
    """
    Languoid = apps.get_model('metadata', 'Languoid')
    Languoid.objects.all().update(level_glottolog='')


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0087_rename_level_languoid_level_nal'),
    ]

    operations = [
        migrations.AddField(
            model_name='languoid',
            name='level_glottolog',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('language', 'Language'), ('dialect', 'Dialect')], max_length=15),
        ),
        migrations.RunPython(copy_level_nal_to_glottolog, reverse_migration),
    ]
