# Generated by Django 5.0.14 on 2025-10-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0088_add_level_glottolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languoid',
            name='level_glottolog',
            field=models.CharField(choices=[('family', 'Family'), ('language', 'Language'), ('dialect', 'Dialect')], max_length=15),
        ),
    ]
