# Generated by Django 5.0.14 on 2025-10-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0089_make_level_glottolog_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languoid',
            name='alt_name',
        ),
    ]
