# Generated by Django 5.0.14 on 2025-10-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0090_remove_alt_name_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languoid',
            name='dialects_languoids',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='language',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='language_languoid',
        ),
    ]
