# Generated by Django 5.0.14 on 2025-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0091_remove_empty_language_dialect_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languoid',
            name='iso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='languoid',
            name='tribes',
            field=models.TextField(blank=True),
        ),
    ]
