# Generated by Django 5.0.14 on 2025-10-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0092_alter_languoid_iso_alter_languoid_tribes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languoid',
            name='family',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='family_abbrev',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='pri_subgroup',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='pri_subgroup_abbrev',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='pri_subgroup_id',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='sec_subgroup',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='sec_subgroup_abbrev',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='sec_subgroup_id',
        ),
    ]
