# Generated by Django 5.0.14 on 2025-10-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0093_remove_denormalized_hierarchy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languoid',
            name='dialects',
        ),
        migrations.RemoveField(
            model_name='languoid',
            name='dialects_ids',
        ),
    ]
