# Generated by Django 5.0.14 on 2025-11-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0094_remove_languoid_dialects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languoid',
            name='level_nal',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('subfamily', 'Primary Subfamily'), ('subsubfamily', 'Secondary Subfamily'), ('language', 'Language'), ('dialect', 'Dialect')], max_length=15),
        ),
    ]
