# Generated by Django 5.0.14 on 2025-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0096_remove_collaboratorname_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
