# Generated by Django 5.0.14 on 2025-11-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0097_add_collaborator_name_suffix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='name',
            new_name='full_name',
        ),
    ]
