# Generated by Django 5.0.14 on 2025-11-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0098_rename_name_to_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='firstname',
            new_name='first_names',
        ),
    ]
