# Generated by Django 5.0.14 on 2025-11-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0099_rename_firstname_to_first_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='lastname',
            new_name='last_names',
        ),
    ]
