# Generated by Django 5.0.14 on 2025-11-04 00:20

from django.db import migrations, models
import django.contrib.postgres.fields


def migrate_other_names_to_array(apps, schema_editor):
    """
    Convert other_names CharField to ArrayField.
    
    Handles:
    - Empty/null values → empty array
    - Comma-separated values → split into array
    - Semicolon-separated values → split into array  
    - Single values (no delimiter) → single-item array
    - Special characters (parentheses, apostrophes, etc.) → preserved
    """
    Collaborator = apps.get_model('metadata', 'Collaborator')
    
    # Delimiters in priority order (based on data analysis)
    # Comma is most common (51 records), semicolon is rare (3 records)
    delimiters = [',', ';']
    
    migrated_count = 0
    empty_count = 0
    single_value_count = 0
    multi_value_count = 0
    
    # Process all collaborators
    for collaborator in Collaborator.objects.all():
        old_value = collaborator.other_names_old
        
        # Handle empty/null values
        if not old_value or not old_value.strip():
            collaborator.other_names = []
            collaborator.save(update_fields=['other_names'])
            empty_count += 1
            continue
        
        # Try each delimiter to parse the value
        names_list = None
        for delimiter in delimiters:
            if delimiter in old_value:
                # Split by delimiter and clean each part
                names_list = [
                    name.strip() 
                    for name in old_value.split(delimiter) 
                    if name.strip()  # Remove empty strings
                ]
                multi_value_count += 1
                break
        
        # No delimiter found - treat as single name
        if names_list is None:
            names_list = [old_value.strip()]
            single_value_count += 1
        
        # Save the array
        collaborator.other_names = names_list
        collaborator.save(update_fields=['other_names'])
        migrated_count += 1
    
    # Print migration summary
    print(f"\n{'='*80}")
    print(f"✅ other_names Migration Complete")
    print(f"{'='*80}")
    print(f"  Total processed:        {Collaborator.objects.count()}")
    print(f"  Empty values:           {empty_count}")
    print(f"  Single names:           {single_value_count}")
    print(f"  Multiple names (split): {multi_value_count}")
    print(f"  Successfully migrated:  {migrated_count}")
    print(f"{'='*80}\n")


def reverse_migrate_other_names_to_string(apps, schema_editor):
    """
    Reverse migration: Convert ArrayField back to comma-separated CharField.
    This allows rollback if needed.
    """
    Collaborator = apps.get_model('metadata', 'Collaborator')
    
    for collaborator in Collaborator.objects.all():
        if collaborator.other_names:
            # Join array with comma and space
            collaborator.other_names_old = ', '.join(collaborator.other_names)
        else:
            # Empty array becomes empty string
            collaborator.other_names_old = ''
        
        collaborator.save(update_fields=['other_names_old'])
    
    print(f"\n✅ Reversed migration: Converted {Collaborator.objects.count()} records back to CharField\n")


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0100_rename_lastname_to_last_names'),
    ]

    operations = [
        # Step 1: Rename old field to temporary name
        migrations.RenameField(
            model_name='collaborator',
            old_name='other_names',
            new_name='other_names_old',
        ),
        
        # Step 2: Add new ArrayField with same name
        migrations.AddField(
            model_name='collaborator',
            name='other_names',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=list,
                blank=True,
                size=None,
                help_text='Alternative names, spellings, or aliases for this collaborator'
            ),
        ),
        
        # Step 3: Migrate data from old CharField to new ArrayField
        migrations.RunPython(
            migrate_other_names_to_array,
            reverse_migrate_other_names_to_string
        ),
        
        # Step 4: Remove old field
        migrations.RemoveField(
            model_name='collaborator',
            name='other_names_old',
        ),
    ]
