# Generated by Django 5.0.14 on 2025-11-11 17:17

from django.db import migrations, models


def migrate_geographic_data_to_items(apps, schema_editor):
    """
    Migrate Geographic data to Item model.
    
    Since Geographic has a 1:1 relationship with Items (each Geographic
    belongs to exactly one Item, and no Item has more than one Geographic),
    we can safely copy lat/long directly to the Item model.
    """
    Geographic = apps.get_model('metadata', 'Geographic')
    Item = apps.get_model('metadata', 'Item')
    
    # Get all Geographic objects associated with Items
    geographics = Geographic.objects.filter(item__isnull=False).select_related('item')
    
    migrated_count = 0
    for geographic in geographics:
        item = geographic.item
        item.latitude = geographic.lat
        item.longitude = geographic.long
        item.save(update_fields=['latitude', 'longitude'])
        migrated_count += 1
    
    print(f"Migrated {migrated_count} Geographic objects to Item latitude/longitude fields")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Copy data back from Item to Geographic.
    
    Note: This only works if Geographic objects still exist.
    """
    Geographic = apps.get_model('metadata', 'Geographic')
    Item = apps.get_model('metadata', 'Item')
    
    # Get all Items with latitude/longitude
    items = Item.objects.filter(latitude__isnull=False, longitude__isnull=False)
    
    restored_count = 0
    for item in items:
        # Check if a Geographic already exists for this item
        geographic = Geographic.objects.filter(item=item).first()
        if geographic:
            geographic.lat = item.latitude
            geographic.long = item.longitude
            geographic.save(update_fields=['lat', 'long'])
            restored_count += 1
    
    print(f"Restored {restored_count} Geographic objects from Item latitude/longitude fields")


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0102_decommission_dialect_models'),
    ]

    operations = [
        # Add latitude and longitude fields to Item model
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='longitude'),
        ),
        # Migrate data from Geographic to Item
        migrations.RunPython(
            migrate_geographic_data_to_items,
            reverse_code=reverse_migration,
        ),
    ]
