# Generated by Django 5.0.14 on 2025-11-14 03:36

import multiselectfield.db.fields
from django.db import migrations


def calculate_browse_categories_for_existing_items(apps, schema_editor):
    """
    Data migration to calculate browse_categories for all existing items.
    Uses the same logic as the pre_save signal.
    """
    Item = apps.get_model('metadata', 'Item')
    
    # Helper function to safely check if a value is in a field
    # MultiSelectField can return either a list or a comma-separated string
    def field_includes(field_value, check_value):
        if not field_value:
            return False
        if isinstance(field_value, (list, tuple)):
            return check_value in field_value
        if isinstance(field_value, str):
            # Handle comma-separated string (MultiSelectField storage format)
            values = [v.strip() for v in field_value.split(',') if v.strip()]
            return check_value in values
        return check_value == field_value
    
    # Get field values - MultiSelectField may return string or list
    # Convert to list for consistent handling
    def to_list(value):
        if not value:
            return []
        if isinstance(value, (list, tuple)):
            return list(value)
        if isinstance(value, str):
            return [v.strip() for v in value.split(',') if v.strip()]
        return [value]
    
    print(f"\nCalculating browse categories for {Item.objects.count()} items...")
    updated_count = 0
    
    for item in Item.objects.all().iterator():
        categories = []
        
        # Get field values - MultiSelectField may return string or list
        # Convert to list for consistent handling
        lang_desc_type = to_list(item.language_description_type)
        genre = to_list(item.genre)
        resource_type = item.resource_type or ''
        public_event = item.public_event
        
        # Language description materials
        if field_includes(lang_desc_type, 'grammar'):
            categories.append('grammars')
        if field_includes(lang_desc_type, 'grammar-specific-feature'):
            categories.append('specific-features')
        if field_includes(lang_desc_type, 'lexicon-dictionary'):
            categories.append('dictionaries')
        
        # Music categories (check for specific music_* genres)
        if field_includes(genre, 'music_powwow'):
            categories.append('powwow')
        if field_includes(genre, 'music_stomp_dance'):
            categories.append('stomp-dance')
        if field_includes(genre, 'music_hymn'):
            categories.append('hymns')
        if field_includes(genre, 'music_for_children'):
            categories.append('for-children-music')
        if field_includes(genre, 'music_forty_nine'):
            categories.append('forty-nine')
        if field_includes(genre, 'music_hand_game'):
            categories.append('hand-game')
        if field_includes(genre, 'music_native_american_church'):
            categories.append('nac')
        if field_includes(genre, 'music_war_dance'):
            categories.append('war-dance')
        if field_includes(genre, 'music_round_dance'):
            categories.append('round-dance')
        if field_includes(genre, 'music_sundance'):
            categories.append('sundance')
        
        # Other ceremonial (music_ceremonial, but excluding specific types)
        if field_includes(genre, 'music_ceremonial'):
            excluded = ['music_powwow', 'music_stomp_dance', 'music_hymn', 'music_for_children', 
                       'music_forty_nine', 'music_hand_game', 'music_native_american_church', 
                       'music_war_dance', 'music_round_dance', 'music_sundance']
            if not any(field_includes(genre, exc) for exc in excluded):
                categories.append('other-ceremonial')
        
        # Educational materials
        if field_includes(genre, 'educational_material_family'):
            categories.append('for-families')
        if field_includes(genre, 'educational_material_teachers'):
            categories.append('for-teachers')
        if field_includes(genre, 'educational_material_learners'):
            categories.append('for-learners')
        if field_includes(genre, 'educational_material_planning'):
            categories.append('for-administrators')
        
        # Texts (various primary-text subcategories)
        if field_includes(lang_desc_type, 'primary-text-igt'):
            categories.append('interlinear-glossed-texts')
        
        if field_includes(lang_desc_type, 'primary-text'):
            if field_includes(genre, 'traditional_story'):
                categories.append('literature-and-stories')
            if field_includes(genre, 'conversation'):
                categories.append('conversation')
            if field_includes(genre, 'ceremonial'):
                categories.append('religious-material')
            if field_includes(genre, 'correspondence'):
                categories.append('correspondence')
            if field_includes(genre, 'narrative'):
                categories.append('narrative')
            if field_includes(genre, 'popular_production'):
                categories.append('popular-media-text')
        
        # Videos (including audio-video)
        if resource_type in ('video', 'audio-video'):
            # For children videos - check both general for_children and music_for_children
            if field_includes(genre, 'for_children') or field_includes(genre, 'music_for_children'):
                categories.append('for-children-video')
            if public_event:
                categories.append('events')
            if field_includes(genre, 'popular_production'):
                categories.append('popular-media-video')
        
        # Set the calculated categories, sorted according to BROWSE_CATEGORY_CHOICES order
        # Remove duplicates first
        unique_categories = list(set(categories))
        
        # Sort according to the order defined in BROWSE_CATEGORY_CHOICES
        from metadata.models import BROWSE_CATEGORY_CHOICES
        # Create a lookup dict: category_value -> index in BROWSE_CATEGORY_CHOICES
        category_order = {choice[0]: idx for idx, choice in enumerate(BROWSE_CATEGORY_CHOICES)}
        # Sort by index in BROWSE_CATEGORY_CHOICES, with any unknown values at the end
        sorted_categories = sorted(unique_categories, key=lambda x: category_order.get(x, 9999))
        
        item.browse_categories = sorted_categories
        item.save(update_fields=['browse_categories'])
        updated_count += 1
        
        if updated_count % 100 == 0:
            print(f"  Processed {updated_count} items...")
    
    print(f"✓ Successfully calculated browse categories for {updated_count} items\n")


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0103_add_latitude_longitude_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='browse_categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('grammars', 'Grammars'), ('specific-features', 'Specific features'), ('dictionaries', 'Dictionaries'), ('powwow', 'Powwow'), ('stomp-dance', 'Stomp dance'), ('hymns', 'Hymns'), ('other-ceremonial', 'Other ceremonial'), ('for-children-music', 'For children (Music)'), ('forty-nine', '49'), ('hand-game', 'Hand game'), ('nac', 'NAC'), ('war-dance', 'War dance'), ('round-dance', 'Round dance'), ('sundance', 'Sundance'), ('for-families', 'For families'), ('for-teachers', 'For teachers'), ('for-learners', 'For learners'), ('for-administrators', 'For administrators'), ('interlinear-glossed-texts', 'Interlinear glossed texts'), ('literature-and-stories', 'Literature and stories'), ('conversation', 'Conversation'), ('religious-material', 'Religious material'), ('correspondence', 'Correspondence'), ('narrative', 'Narrative'), ('popular-media-text', 'Popular media (Text)'), ('for-children-video', 'For children (Video)'), ('events', 'Events'), ('popular-media-video', 'Popular media (Video)')], editable=False, max_length=385),
        ),
        migrations.RunPython(
            calculate_browse_categories_for_existing_items,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
