# Generated by Django 5.0.14 on 2026-05-24 05:18

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0105_remove_permission_to_publish_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='browse_categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('for-administrators', 'For administrators'), ('for-families', 'For families'), ('for-learners', 'For learners'), ('for-teachers', 'For teachers'), ('dictionaries', 'Dictionaries'), ('grammars', 'Grammars'), ('specific-features', 'Specific features'), ('forty-nine', '49'), ('for-children-music', 'For children (Music)'), ('hand-game', 'Hand game'), ('hymns', 'Hymns'), ('nac', 'Native American Church'), ('other-ceremonial', 'Other ceremonial'), ('powwow', 'Powwow'), ('round-dance', 'Round dance'), ('stomp-dance', 'Stomp dance'), ('sundance', 'Sundance'), ('war-dance', 'War dance'), ('conversation', 'Conversation'), ('correspondence', 'Correspondence'), ('interlinear-glossed-texts', 'Interlinear glossed texts'), ('literature-and-stories', 'Literature and stories'), ('narrative', 'Narrative'), ('popular-media-text', 'Popular media (Text)'), ('religious-material', 'Religious material'), ('events', 'Events'), ('for-children-video', 'For children (Video)'), ('popular-media-video', 'Popular media (Video)')], editable=False, max_length=385),
        ),
    ]
