# Generated by Django 3.2 on 2025-03-01 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0073_languoid_alt_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('NEEDS_REVISION', 'Needs Revision'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('INCOMPLETE', 'Incomplete/Closed')], default='DRAFT', max_length=20)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('format_version', models.CharField(max_length=50)),
                ('file_count', models.IntegerField(default=0)),
                ('deposit_type', models.CharField(choices=[('NEW', 'New Deposit'), ('CHANGE', 'Change Request')], default='NEW', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('collections', models.ManyToManyField(related_name='deposit_collections', to='metadata.Collection')),
                ('draft_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_deposits', to=settings.AUTH_USER_MODEL)),
                ('involved_users', models.ManyToManyField(related_name='involved_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_at'],
                'permissions': [('can_review_deposits', 'Can review deposits'), ('can_manage_deposits', 'Can manage all deposits')],
            },
        ),
    ]
