# Generated by Django 3.2 on 2025-03-01 23:46

import deposits.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=deposits.storage.DepositStorage(), upload_to='%Y/%m/%d')),
                ('filename', models.CharField(max_length=255)),
                ('filetype', models.CharField(blank=True, max_length=100)),
                ('filesize', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_metadata_file', models.BooleanField(default=False)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='deposits.deposit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
