# Generated by Django 3.2 on 2025-03-05 09:26

import deposits.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfile',
            name='file',
            field=models.FileField(storage=deposits.storage.DepositStorage(), upload_to=''),
        ),
    ]
