"""
Django settings for archive project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import ast
import environ
from .deploychoice import *
import logging.config
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


if 'deploychoice' in globals():
    # The variable is defined, use its value
    deploy = deploychoice
else:
    # The variable is not defined, use False
    deploy = False

if deploy:
    pass
else:
    env = environ.Env(
        # set casting, default value
        DEBUG=(bool, False)
    )
    # Take environment variables from .env file
    environ.Env.read_env(os.path.join(BASE_DIR, '../.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if deploy:
    SECRET_KEY = os.getenv('SECRET_KEY')
else:
    SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

if deploy:
    DEBUG = os.getenv('DEBUG') == "True"
else:
    DEBUG = env('DEBUG')

#ALLOWED_HOSTS =
if deploy:
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
else:
    ALLOWED_HOSTS = env("ALLOWED_HOSTS").split(",")
ALLOWED_HOSTS = [] if not any(ALLOWED_HOSTS) else ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'multiselectfield',
    'video_encoding',
    'django_filters',
    'rest_framework',
    'oauth2_provider',
    'drf_spectacular',  
    'django_select2',
    'metadata',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'archive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'archive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if deploy:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.getenv('DBNAME'),
            'USER': os.getenv('DBUSER'),
            'PASSWORD': os.getenv('DBPASS'),
            'HOST': os.getenv('DBHOST'),
            'PORT': os.getenv('DBPORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env('DBNAME'),
            'USER': env('DBUSER'),
            'PASSWORD': env('DBPASS'),
            'HOST': env('DBHOST'),
            'PORT': env('DBPORT'),
        }
    }
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
#STATIC_URL = '/dj/static/'
#MEDIA_URL = '/dj/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static-files')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
if deploy:
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    ADMINS = ast.literal_eval(os.getenv('ADMINS'))
else:
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
    ADMINS = ast.literal_eval(env('ADMINS'))

##for serving at subpath /django
#FORCE_SCRIPT_NAME = '/dj'
#USE_X_FORWARDED_HOST = True
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 100
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Archive API',
    'DESCRIPTION': 'API for accessing the Archive collection database...',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [
        {'SessionAuth': []},
        {'Bearer': []}
    ],
    'AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'TAGS': [
        {'name': 'items', 'description': 'Operations with archive items'},
        {'name': 'collections', 'description': 'Operations with collections'},
        {'name': 'languoids', 'description': 'Operations with languoids'},
        {'name': 'collaborators', 'description': 'Operations with collaborators'},
    ],
}

# OAuth2 Configuration
OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Read access to public items',
        'write': 'Write access',
    },
    'DEFAULT_SCOPES': ['read'],
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 36000,
    'ALLOWED_GRANT_TYPES': [
        'client_credentials',
        'password',
        'authorization_code',
        'implicit'
    ],
    'CLIENT_ID_GENERATOR_CLASS': 'oauth2_provider.generators.ClientIdGenerator',
    'CLIENT_SECRET_GENERATOR_CLASS': 'oauth2_provider.generators.ClientSecretGenerator',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'oauth2_provider': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'oauthlib': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}

# Add this near the top of your settings.py file
SERVER_ROLE = os.environ.get('SERVER_ROLE', 'public')
PUBLIC_SERVER_URL = os.environ.get('PUBLIC_SERVER_URL', '')
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')
REDIS_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')

# For Docker deployments, make sure we don't use localhost
if 'localhost' in REDIS_URL and SERVER_ROLE in ('public', 'private'):
    # Replace localhost with the service name in docker-compose
    REDIS_URL = REDIS_URL.replace('localhost', 'redis')

# Add password to Redis URL if it exists
if REDIS_PASSWORD and '://' in REDIS_URL:
    protocol, rest = REDIS_URL.split('://', 1)
    if '@' not in rest:
        host_part = rest
        REDIS_URL = f"{protocol}://:{REDIS_PASSWORD}@{host_part}"

# Configure Celery based on server role
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# For private server, also keep track of public Redis for communication
if SERVER_ROLE == 'private':
    PUBLIC_REDIS_URL = os.environ.get('PUBLIC_REDIS_URL', '')

# File storage paths based on server role
if SERVER_ROLE == 'public':
    CELERY_TASK_ROUTES = {
        'metadata.tasks.*': {'queue': 'public'},
        'common.tasks.*': {'queue': 'common'},
    }
    PUBLIC_STORAGE_PATH = os.path.join(BASE_DIR, 'public_storage')
    TEMP_STORAGE_PATH = os.path.join(BASE_DIR, 'temp_storage')
    SEQUESTERED_INCOMING_PATH = os.path.join(BASE_DIR, 'sequestered_incoming')
    SEQUESTERED_OUTGOING_PATH = os.path.join(BASE_DIR, 'sequestered_outgoing')
    
else:  # private
    CELERY_TASK_ROUTES = {
        'metadata.tasks.*': {'queue': 'private'},
        'common.tasks.*': {'queue': 'common'},
    }
    MAIN_STORAGE_PATH = os.path.join(BASE_DIR, 'main_storage')
    SEQUESTERED_INCOMING_PATH = os.path.join(BASE_DIR, 'sequestered_incoming')

CELERY_BEAT_SCHEDULE = {
    'update-collection-item-counts': {
        'task': 'metadata.tasks.update_collection_item_counts',
        'schedule': crontab(hour=2, minute=0),  # Run at 2 AM every day
    },
    'cleanup-temp-files': {
        'task': 'metadata.tasks.cleanup_temp_files',
        'schedule': crontab(hour='*/6', minute=0),  # Run every 6 hours
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
