"""
Django settings for archive project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import ast
import environ
from .deploychoice import *
import logging.config
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


if 'deploychoice' in globals():
    # The variable is defined, use its value
    deploy = deploychoice
else:
    # The variable is not defined, use False
    deploy = False

if deploy:
    pass
else:
    env = environ.Env(
        # set casting, default value
        DEBUG=(bool, False)
    )
    # Take environment variables from .env file
    environ.Env.read_env(os.path.join(BASE_DIR, '../.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if deploy:
    SECRET_KEY = os.getenv('SECRET_KEY')
else:
    SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

if deploy:
    DEBUG = os.getenv('DEBUG') == "True"
else:
    DEBUG = env('DEBUG')

#ALLOWED_HOSTS =
if deploy:
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
else:
    ALLOWED_HOSTS = env("ALLOWED_HOSTS").split(",")
ALLOWED_HOSTS = [] if not any(ALLOWED_HOSTS) else ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'multiselectfield',
    # 'video_encoding',  # Removed for Django 5.0 compatibility
    'django_filters',
    'rest_framework',
    'oauth2_provider',
    'drf_spectacular',  
    'django_select2',
    'corsheaders',  # Enable CORS for React dev server
    'metadata',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top for CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'archive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'archive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if deploy:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.getenv('DBNAME'),
            'USER': os.getenv('DBUSER'),
            'PASSWORD': os.getenv('DBPASS'),
            'HOST': os.getenv('DBHOST'),
            'PORT': os.getenv('DBPORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env('DBNAME'),
            'USER': env('DBUSER'),
            'PASSWORD': env('DBPASS'),
            'HOST': env('DBHOST'),
            'PORT': env('DBPORT'),
        }
    }
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
#STATIC_URL = '/dj/static/'
#MEDIA_URL = '/dj/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static-files')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
if deploy:
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    ADMINS = ast.literal_eval(os.getenv('ADMINS'))
else:
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
    ADMINS = ast.literal_eval(env('ADMINS'))

##for serving at subpath /django
#FORCE_SCRIPT_NAME = '/dj'
#USE_X_FORWARDED_HOST = True
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 100
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Archive API',
    'DESCRIPTION': 'API for accessing the Archive collection database...',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [
        {'SessionAuth': []},
        {'Bearer': []}
    ],
    'AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'TAGS': [
        {'name': 'items', 'description': 'Operations with archive items'},
        {'name': 'collections', 'description': 'Operations with collections'},
        {'name': 'languoids', 'description': 'Operations with languoids'},
        {'name': 'collaborators', 'description': 'Operations with collaborators'},
        {'name': 'map', 'description': 'Geographic data for map visualization'},
    ],
    # Exclude internal API from public documentation
    'PREPROCESSING_HOOKS': [
        'archive.spectacular_hooks.exclude_internal_api',
    ],
}

# OAuth2 Configuration
OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Read access to public items',
        'write': 'Write access',
    },
    'DEFAULT_SCOPES': ['read'],
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 36000,
    'ALLOWED_GRANT_TYPES': [
        'client_credentials',
        'password',
        'authorization_code',
        'implicit'
    ],
    'CLIENT_ID_GENERATOR_CLASS': 'oauth2_provider.generators.ClientIdGenerator',
    'CLIENT_SECRET_GENERATOR_CLASS': 'oauth2_provider.generators.ClientSecretGenerator',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'oauth2_provider': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'oauthlib': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}

# Add this near the top of your settings.py file
SERVER_ROLE = os.environ.get('SERVER_ROLE', 'public')
PUBLIC_SERVER_URL = os.environ.get('PUBLIC_SERVER_URL', '')
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')

# Build Redis URL from components (best practice)
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_DB = os.environ.get('REDIS_DB', '0')

# Construct Redis URL with proper authentication
if REDIS_PASSWORD:
    REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
else:
    REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

# Detect environment (Docker vs development)
def is_docker():
    """Check if we're running in a Docker container by looking for specific env markers"""
    return os.path.exists('/.dockerenv') or os.environ.get('DOCKER_CONTAINER') == 'true'

def can_resolve_hostname(hostname):
    """Check if a hostname can be resolved"""
    try:
        import socket
        socket.gethostbyname(hostname)
        return True
    except socket.error:
        return False

# Configure Celery based on server role
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# For private server, also keep track of public Redis for communication
if SERVER_ROLE == 'private':
    PUBLIC_REDIS_URL = os.environ.get('PUBLIC_REDIS_URL', '')

# Base storage path from environment or default to project directory
HOST_STORAGE_BASE = os.environ.get('HOST_STORAGE_PATH', BASE_DIR)

# File storage paths based on server role
if SERVER_ROLE == 'public':
    CELERY_TASK_ROUTES = {
        'metadata.tasks.*': {'queue': 'public'},
        'common.tasks.*': {'queue': 'common'},
    }
    
    # Define the storage paths - consistent between Docker and development
    if is_docker():
        PUBLIC_STORAGE_PATH = '/app/public_storage'
    else:
        PUBLIC_STORAGE_PATH = os.path.join(HOST_STORAGE_BASE, 'public_storage')
    TEMP_STORAGE_PATH = os.path.join(PUBLIC_STORAGE_PATH, '..', 'temp_storage')
    SEQUESTERED_INCOMING_PATH = os.path.join(PUBLIC_STORAGE_PATH, '..', 'sequestered_incoming')
    SEQUESTERED_OUTGOING_PATH = os.path.join(PUBLIC_STORAGE_PATH, '..', 'sequestered_outgoing')
else:  # private server
    CELERY_TASK_ROUTES = {
        'metadata.tasks.*': {'queue': 'private'},
        'common.tasks.*': {'queue': 'common'},
    }
    
    # Define the storage paths - consistent between Docker and development
    if is_docker():
        MAIN_STORAGE_PATH = '/app/main_storage'
    else:
        MAIN_STORAGE_PATH = os.path.join(HOST_STORAGE_BASE, 'main_storage')
    TEMP_STORAGE_PATH = os.path.join(MAIN_STORAGE_PATH, '..', 'temp_storage')
    SEQUESTERED_INCOMING_PATH = os.path.join(MAIN_STORAGE_PATH, '..', 'sequestered_incoming')
    SEQUESTERED_OUTGOING_PATH = os.path.join(MAIN_STORAGE_PATH, '..', 'sequestered_outgoing')

CELERY_BEAT_SCHEDULE = {
    'update-collection-item-counts': {
        'task': 'metadata.tasks.update_collection_item_counts',
        'schedule': crontab(hour=2, minute=0),  # Run at 2 AM every day
    },
    'cleanup-temp-files': {
        'task': 'metadata.tasks.cleanup_temp_files',
        'schedule': crontab(hour='*/6', minute=0),  # Run every 6 hours
    },
    'warm-languoid-list-cache': {
        'task': 'metadata.tasks.warm_languoid_list_cache',
        'schedule': crontab(minute='*/9'),  # Run every 9 minutes
        'options': {
            'priority': 5,  # Medium priority - background maintenance
        }
    },
}

# Cache configuration
# Using Redis for shared cache across Gunicorn workers and persistence
# Django 5.0 built-in RedisCache backend
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': 'archive',
        'TIMEOUT': 600,  # Default 10 minutes
    }
}

# django-select2 cache backend setting
SELECT2_CACHE_BACKEND = 'default'

# =============================================================================
# CORS Configuration for React Development Server
# =============================================================================

# Allow React dev server (localhost:3000) to make requests to Django (localhost:8000)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Allow credentials (cookies, authorization headers) to be sent with CORS requests
CORS_ALLOW_CREDENTIALS = True

# Allow all headers for development (can be restricted in production)
CORS_ALLOW_ALL_HEADERS = True

# Expose headers that the frontend might need
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# Allow common HTTP methods
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# =============================================================================
# CSRF Configuration for React Development Server
# =============================================================================

# Allow React dev server origins for CSRF validation
# Also allow production domains from environment variable
if deploy:
    # In production, read from environment variable
    csrf_origins_str = os.getenv('CSRF_TRUSTED_ORIGINS', '')
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_str.split(',') if origin.strip()]
else:
    # In development, use localhost
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

# Allow CSRF cookies to be sent from React dev server
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG  # True in production with HTTPS, False in development

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
